fix: extension registry null pointer
fixes this compilation error:

``` [81/222] Building CXX object
vicinae/CMakeFiles/vicinae.dir/src/main.cpp.o
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp: In
function ‘int startDaemon()’:
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp:168:60:
warning: ‘this’ pointer is null [-Wnonnull] 168 | for (const auto
&manifest : extensionRegistry->scanAll()) { | ^ In file included from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/include/extension/extension.hpp:5,
from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/extension/manager/extension-manager.hpp:9,
from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp:46:
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/services/extension-registry/extension-registry.hpp:61:34:
note: in a call to non-static member function
‘std::vector<ExtensionManifest> ExtensionRegistry::scanAll()’ 61 |
std::vector<ExtensionManifest> scanAll(); | ^~~~~~~ ```

by using the `extensionRegistry`'s service instead of the
`extensionRegistry` variable (after `std::move` the variable is null)